# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'design.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(960, 540)
        MainWindow.setMinimumSize(QtCore.QSize(960, 540))
        MainWindow.setMaximumSize(QtCore.QSize(16777215, 16777215))
        MainWindow.setAcceptDrops(False)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/Logos/Resources/Logos/Logo_white.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setAutoFillBackground(False)
        MainWindow.setStyleSheet("QPushButton {\n"
"    border: none;\n"
"}\n"
"\n"
"QMainWindow {\n"
"     background-color: #1c1f29; \n"
"    /* background: transparent; */\n"
"    background-origin: content;\n"
"    background-image: url(:/Backgrounds/Resources/Backgrounds/background_3.svg);\n"
"}\n"
"\n"
"QStatusBar {\n"
"    /* background-color: #12141c; */\n"
"    background-color: #31374d;\n"
"    color: white;\n"
"}\n"
"\n"
"QListWidget {\n"
"    border-width: 3px;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"/* SCROLL BARS */\n"
"QScrollBar:horizontal {\n"
"    border: none;\n"
"    background: rgb(52, 59, 72);\n"
"    height: 14px;\n"
"    margin: 0px 21px 0 21px;\n"
"    border-radius: 0px;\n"
"}\n"
"QScrollBar::handle:horizontal {\n"
"    background: rgb(85, 170, 255);\n"
"    min-width: 25px;\n"
"    border-radius: 7px\n"
"}\n"
"QScrollBar::add-line:horizontal {\n"
"    border: none;\n"
"    background: rgb(55, 63, 77);\n"
"    width: 20px;\n"
"    border-top-right-radius: 7px;\n"
"    border-bottom-right-radius: 7px;\n"
"    subcontrol-position: right;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::sub-line:horizontal {\n"
"    border: none;\n"
"    background: rgb(55, 63, 77);\n"
"    width: 20px;\n"
"    border-top-left-radius: 7px;\n"
"    border-bottom-left-radius: 7px;\n"
"    subcontrol-position: left;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::up-arrow:horizontal, QScrollBar::down-arrow:horizontal\n"
"{\n"
"     background: none;\n"
"}\n"
"QScrollBar::add-page:horizontal, QScrollBar::sub-page:horizontal\n"
"{\n"
"     background: none;\n"
"}\n"
" QScrollBar:vertical {\n"
"    border: none;\n"
"    background: rgb(52, 59, 72);\n"
"    width: 14px;\n"
"    margin: 21px 0 21px 0;\n"
"    border-radius: 0px;\n"
" }\n"
" QScrollBar::handle:vertical {    \n"
"    background: rgb(85, 170, 255);\n"
"    min-height: 25px;\n"
"    border-radius: 7px\n"
" }\n"
" QScrollBar::add-line:vertical {\n"
"     border: none;\n"
"    background: rgb(55, 63, 77);\n"
"     height: 20px;\n"
"    border-bottom-left-radius: 7px;\n"
"    border-bottom-right-radius: 7px;\n"
"     subcontrol-position: bottom;\n"
"     subcontrol-origin: margin;\n"
" }\n"
" QScrollBar::sub-line:vertical {\n"
"    border: none;\n"
"    background: rgb(55, 63, 77);\n"
"     height: 20px;\n"
"    border-top-left-radius: 7px;\n"
"    border-top-right-radius: 7px;\n"
"     subcontrol-position: top;\n"
"     subcontrol-origin: margin;\n"
" }\n"
" QScrollBar::up-arrow:vertical, QScrollBar::down-arrow:vertical {\n"
"     background: none;\n"
" }\n"
"\n"
" QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical {\n"
"     background: none;\n"
" }\n"
"\n"
"/* SLIDERS */\n"
"QSlider::groove:horizontal {\n"
"    border-radius: 9px;\n"
"    height: 18px;\n"
"    margin: 0px;\n"
"    background-color: rgb(52, 59, 72);\n"
"}\n"
"QSlider::groove:horizontal:hover {\n"
"    background-color: rgb(55, 62, 76);\n"
"}\n"
"QSlider::handle:horizontal {\n"
"    background-color: rgb(85, 170, 255);\n"
"    border: none;\n"
"    height: 18px;\n"
"    width: 18px;\n"
"    margin: 0px;\n"
"    border-radius: 9px;\n"
"}\n"
"QSlider::handle:horizontal:hover {\n"
"    background-color: rgb(105, 180, 255);\n"
"}\n"
"QSlider::handle:horizontal:pressed {\n"
"    background-color: rgb(65, 130, 195);\n"
"}\n"
"\n"
"QSlider::groove:vertical {\n"
"    border-radius: 9px;\n"
"    width: 18px;\n"
"    margin: 0px;\n"
"    background-color: rgb(52, 59, 72);\n"
"}\n"
"QSlider::groove:vertical:hover {\n"
"    background-color: rgb(55, 62, 76);\n"
"}\n"
"QSlider::handle:vertical {\n"
"    background-color: rgb(85, 170, 255);\n"
"    border: none;\n"
"    height: 18px;\n"
"    width: 18px;\n"
"    margin: 0px;\n"
"    border-radius: 9px;\n"
"}\n"
"QSlider::handle:vertical:hover {\n"
"    background-color: rgb(105, 180, 255);\n"
"}\n"
"QSlider::handle:vertical:pressed {\n"
"    background-color: rgb(65, 130, 195);\n"
"}\n"
"\n"
"/*QListWidget*/\n"
"QListWidget {\n"
"    background-color: rgb(27, 29, 35);\n"
"    border-radius: 5px;\n"
"    padding: 10px;\n"
"    color: white;\n"
"    border: 2px solid rgb(64, 71, 88);\n"
"}\n"
"QListWidget:hover {\n"
"    border: 2px solid rgb(75, 82, 99);\n"
"}\n"
"QListWidget:focus {\n"
"    border: 2px solid rgb(85, 170, 255);\n"
"}\n"
"\n"
"QToolTip {\n"
"    color: #ffffff;\n"
"    background-color: rgba(27, 29, 35, 160);\n"
"    border: 1px solid rgb(40, 40, 40);\n"
"    border-radius: 2px;\n"
"}\n"
"\n"
"/* QLineEdit */\n"
"QLineEdit {\n"
"    background-color: rgb(20, 20, 20);\n"
"    border-radius: 3px;\n"
"    border: 2px solid rgb(64, 71, 88);\n"
"    padding-left: 10px;\n"
"}\n"
"QLineEdit:hover {\n"
"    border: 2px solid rgb(64, 71, 88);\n"
"}\n"
"QLineEdit:focus {\n"
"    border: 2px solid rgb(85, 170, 255);\n"
"}")
        MainWindow.setIconSize(QtCore.QSize(256, 128))
        MainWindow.setDocumentMode(False)
        MainWindow.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("background-color: #38618С;")
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.main_frame = QtWidgets.QFrame(self.centralwidget)
        self.main_frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.main_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.main_frame.setObjectName("main_frame")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.main_frame)
        self.verticalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_8.setSpacing(0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.frame_custom_bar = QtWidgets.QFrame(self.main_frame)
        self.frame_custom_bar.setMinimumSize(QtCore.QSize(0, 48))
        self.frame_custom_bar.setMaximumSize(QtCore.QSize(16777215, 48))
        self.frame_custom_bar.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.frame_custom_bar.setAutoFillBackground(False)
        self.frame_custom_bar.setStyleSheet("background-color: #31374d;\n"
"color: white;")
        self.frame_custom_bar.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_custom_bar.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_custom_bar.setObjectName("frame_custom_bar")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_custom_bar)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(3)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frame_spacer_custom_bar = QtWidgets.QFrame(self.frame_custom_bar)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_spacer_custom_bar.sizePolicy().hasHeightForWidth())
        self.frame_spacer_custom_bar.setSizePolicy(sizePolicy)
        self.frame_spacer_custom_bar.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_spacer_custom_bar.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_spacer_custom_bar.setObjectName("frame_spacer_custom_bar")
        self.horizontalLayout_21 = QtWidgets.QHBoxLayout(self.frame_spacer_custom_bar)
        self.horizontalLayout_21.setContentsMargins(10, 0, 0, 0)
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        self.frame_2 = QtWidgets.QFrame(self.frame_spacer_custom_bar)
        self.frame_2.setMinimumSize(QtCore.QSize(48, 48))
        self.frame_2.setMaximumSize(QtCore.QSize(48, 48))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_22 = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout_22.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_22.setObjectName("horizontalLayout_22")
        self.label_logo = QtWidgets.QLabel(self.frame_2)
        self.label_logo.setMinimumSize(QtCore.QSize(34, 34))
        self.label_logo.setMaximumSize(QtCore.QSize(36, 36))
        self.label_logo.setText("")
        self.label_logo.setPixmap(QtGui.QPixmap(":/Logos/Resources/Logos/Logo_white.svg"))
        self.label_logo.setScaledContents(True)
        self.label_logo.setObjectName("label_logo")
        self.horizontalLayout_22.addWidget(self.label_logo)
        self.horizontalLayout_21.addWidget(self.frame_2, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.label_title = QtWidgets.QLabel(self.frame_spacer_custom_bar)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_title.sizePolicy().hasHeightForWidth())
        self.label_title.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_title.setFont(font)
        self.label_title.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_title.setObjectName("label_title")
        self.horizontalLayout_21.addWidget(self.label_title)
        self.horizontalLayout_2.addWidget(self.frame_spacer_custom_bar, 0, QtCore.Qt.AlignVCenter)
        self.frame_hide_button = QtWidgets.QFrame(self.frame_custom_bar)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_hide_button.sizePolicy().hasHeightForWidth())
        self.frame_hide_button.setSizePolicy(sizePolicy)
        self.frame_hide_button.setMinimumSize(QtCore.QSize(48, 48))
        self.frame_hide_button.setMaximumSize(QtCore.QSize(1000, 1000))
        self.frame_hide_button.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_hide_button.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_hide_button.setObjectName("frame_hide_button")
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout(self.frame_hide_button)
        self.horizontalLayout_18.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_18.setSpacing(0)
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.button_hide = QtWidgets.QPushButton(self.frame_hide_button)
        self.button_hide.setMinimumSize(QtCore.QSize(48, 48))
        self.button_hide.setMaximumSize(QtCore.QSize(1000, 1000))
        self.button_hide.setStyleSheet("QPushButton {\n"
"    background-color #31374d;\n"
"    color: white;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(57, 65, 80);\n"
"}\n"
"QPushButton:pressed {    \n"
"    background-color: rgb(35, 40, 49);\n"
"}")
        self.button_hide.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/Icons/Resources/Icons/remove-outline.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.button_hide.setIcon(icon1)
        self.button_hide.setIconSize(QtCore.QSize(28, 28))
        self.button_hide.setObjectName("button_hide")
        self.horizontalLayout_18.addWidget(self.button_hide, 0, QtCore.Qt.AlignVCenter)
        self.horizontalLayout_2.addWidget(self.frame_hide_button, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.frame_minimize_button = QtWidgets.QFrame(self.frame_custom_bar)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_minimize_button.sizePolicy().hasHeightForWidth())
        self.frame_minimize_button.setSizePolicy(sizePolicy)
        self.frame_minimize_button.setMinimumSize(QtCore.QSize(48, 48))
        self.frame_minimize_button.setMaximumSize(QtCore.QSize(1000, 1000))
        self.frame_minimize_button.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_minimize_button.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_minimize_button.setObjectName("frame_minimize_button")
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout(self.frame_minimize_button)
        self.horizontalLayout_19.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_19.setSpacing(0)
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.button_minimize = QtWidgets.QPushButton(self.frame_minimize_button)
        self.button_minimize.setMinimumSize(QtCore.QSize(48, 48))
        self.button_minimize.setMaximumSize(QtCore.QSize(1000, 1000))
        self.button_minimize.setStyleSheet("QPushButton {\n"
"    background-color #31374d;\n"
"    color: white;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(57, 65, 80);\n"
"}\n"
"QPushButton:pressed {    \n"
"    background-color: rgb(35, 40, 49);\n"
"}")
        self.button_minimize.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/Icons/Resources/Icons/resize-outline.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.button_minimize.setIcon(icon2)
        self.button_minimize.setIconSize(QtCore.QSize(24, 24))
        self.button_minimize.setObjectName("button_minimize")
        self.horizontalLayout_19.addWidget(self.button_minimize)
        self.horizontalLayout_2.addWidget(self.frame_minimize_button, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.frame_close_button = QtWidgets.QFrame(self.frame_custom_bar)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_close_button.sizePolicy().hasHeightForWidth())
        self.frame_close_button.setSizePolicy(sizePolicy)
        self.frame_close_button.setMinimumSize(QtCore.QSize(48, 48))
        self.frame_close_button.setMaximumSize(QtCore.QSize(1000, 1000))
        self.frame_close_button.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_close_button.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_close_button.setObjectName("frame_close_button")
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout(self.frame_close_button)
        self.horizontalLayout_20.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_20.setSpacing(0)
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        self.button_close = QtWidgets.QPushButton(self.frame_close_button)
        self.button_close.setMinimumSize(QtCore.QSize(48, 48))
        self.button_close.setMaximumSize(QtCore.QSize(1000, 1000))
        self.button_close.setStyleSheet("QPushButton {\n"
"    background-color: #31374d;\n"
"    color: white;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(57, 65, 80);\n"
"}\n"
"QPushButton:pressed {    \n"
"    background-color: rgb(200, 0, 0);\n"
"}")
        self.button_close.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/Icons/Resources/Icons/close-outline.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.button_close.setIcon(icon3)
        self.button_close.setIconSize(QtCore.QSize(28, 28))
        self.button_close.setObjectName("button_close")
        self.horizontalLayout_20.addWidget(self.button_close, 0, QtCore.Qt.AlignHCenter)
        self.horizontalLayout_2.addWidget(self.frame_close_button, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.verticalLayout_8.addWidget(self.frame_custom_bar, 0, QtCore.Qt.AlignVCenter)
        self.frame_main_functional = QtWidgets.QFrame(self.main_frame)
        self.frame_main_functional.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_main_functional.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_main_functional.setObjectName("frame_main_functional")
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout(self.frame_main_functional)
        self.horizontalLayout_17.setContentsMargins(-1, 0, -1, 10)
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.left_frame = QtWidgets.QFrame(self.frame_main_functional)
        self.left_frame.setMinimumSize(QtCore.QSize(400, 0))
        self.left_frame.setMaximumSize(QtCore.QSize(800, 16777215))
        self.left_frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.left_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.left_frame.setObjectName("left_frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.left_frame)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(3)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_working_with_uploading_materials = QtWidgets.QFrame(self.left_frame)
        self.frame_working_with_uploading_materials.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_working_with_uploading_materials.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_working_with_uploading_materials.setObjectName("frame_working_with_uploading_materials")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_working_with_uploading_materials)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(5)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.frame_list_uploading_materials = QtWidgets.QFrame(self.frame_working_with_uploading_materials)
        self.frame_list_uploading_materials.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_list_uploading_materials.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_list_uploading_materials.setObjectName("frame_list_uploading_materials")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.frame_list_uploading_materials)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setSpacing(0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.frame_label_uploading_materials = QtWidgets.QFrame(self.frame_list_uploading_materials)
        self.frame_label_uploading_materials.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_label_uploading_materials.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_label_uploading_materials.setObjectName("frame_label_uploading_materials")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_label_uploading_materials)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_uploading_materials_list = QtWidgets.QLabel(self.frame_label_uploading_materials)
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(12)
        self.label_uploading_materials_list.setFont(font)
        self.label_uploading_materials_list.setStyleSheet("color: rgb(230, 230, 230);")
        self.label_uploading_materials_list.setObjectName("label_uploading_materials_list")
        self.horizontalLayout_4.addWidget(self.label_uploading_materials_list)
        self.verticalLayout_7.addWidget(self.frame_label_uploading_materials)
        self.list_uploading_materials = QtWidgets.QListWidget(self.frame_list_uploading_materials)
        self.list_uploading_materials.setMinimumSize(QtCore.QSize(0, 115))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(12)
        self.list_uploading_materials.setFont(font)
        self.list_uploading_materials.setStyleSheet("")
        self.list_uploading_materials.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.list_uploading_materials.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.list_uploading_materials.setObjectName("list_uploading_materials")
        item = QtWidgets.QListWidgetItem()
        self.list_uploading_materials.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.list_uploading_materials.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.list_uploading_materials.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.list_uploading_materials.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.list_uploading_materials.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.list_uploading_materials.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.list_uploading_materials.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.list_uploading_materials.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.list_uploading_materials.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.list_uploading_materials.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.list_uploading_materials.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.list_uploading_materials.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.list_uploading_materials.addItem(item)
        self.verticalLayout_7.addWidget(self.list_uploading_materials)
        self.verticalLayout_4.addWidget(self.frame_list_uploading_materials)
        self.frame_buttons_uploading_materials = QtWidgets.QFrame(self.frame_working_with_uploading_materials)
        self.frame_buttons_uploading_materials.setMaximumSize(QtCore.QSize(16777215, 40))
        self.frame_buttons_uploading_materials.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_buttons_uploading_materials.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_buttons_uploading_materials.setObjectName("frame_buttons_uploading_materials")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.frame_buttons_uploading_materials)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setSpacing(3)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.frame_button_add_uploading = QtWidgets.QFrame(self.frame_buttons_uploading_materials)
        self.frame_button_add_uploading.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_button_add_uploading.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_button_add_uploading.setObjectName("frame_button_add_uploading")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.frame_button_add_uploading)
        self.horizontalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_8.setSpacing(0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.button_add_uploading = QtWidgets.QPushButton(self.frame_button_add_uploading)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_add_uploading.sizePolicy().hasHeightForWidth())
        self.button_add_uploading.setSizePolicy(sizePolicy)
        self.button_add_uploading.setMinimumSize(QtCore.QSize(130, 30))
        self.button_add_uploading.setMaximumSize(QtCore.QSize(16777215, 85))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(10)
        self.button_add_uploading.setFont(font)
        self.button_add_uploading.setAutoFillBackground(False)
        self.button_add_uploading.setStyleSheet("QPushButton {\n"
"    border: 2px solid rgb(52, 59, 72);\n"
"    border-radius: 5px;    \n"
"    background-color: rgb(52, 59, 72);\n"
"    color: white;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(57, 65, 80);\n"
"    border: 2px solid rgb(61, 70, 86);\n"
"}\n"
"QPushButton:pressed {    \n"
"    background-color: rgb(35, 40, 49);\n"
"    border: 2px solid rgb(43, 50, 61);\n"
"}")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/Icons/Resources/Icons/add-circle-outline.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.button_add_uploading.setIcon(icon4)
        self.button_add_uploading.setIconSize(QtCore.QSize(22, 22))
        self.button_add_uploading.setCheckable(False)
        self.button_add_uploading.setAutoRepeat(False)
        self.button_add_uploading.setAutoExclusive(False)
        self.button_add_uploading.setAutoDefault(False)
        self.button_add_uploading.setDefault(False)
        self.button_add_uploading.setFlat(False)
        self.button_add_uploading.setObjectName("button_add_uploading")
        self.horizontalLayout_8.addWidget(self.button_add_uploading)
        self.horizontalLayout_6.addWidget(self.frame_button_add_uploading)
        self.frame_spacer_uploading = QtWidgets.QFrame(self.frame_buttons_uploading_materials)
        self.frame_spacer_uploading.setMinimumSize(QtCore.QSize(0, 0))
        self.frame_spacer_uploading.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_spacer_uploading.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_spacer_uploading.setObjectName("frame_spacer_uploading")
        self.horizontalLayout_6.addWidget(self.frame_spacer_uploading)
        self.frame_button_delete_uploading = QtWidgets.QFrame(self.frame_buttons_uploading_materials)
        self.frame_button_delete_uploading.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_button_delete_uploading.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_button_delete_uploading.setObjectName("frame_button_delete_uploading")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.frame_button_delete_uploading)
        self.horizontalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_9.setSpacing(0)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.button_delete_uploading = QtWidgets.QPushButton(self.frame_button_delete_uploading)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_delete_uploading.sizePolicy().hasHeightForWidth())
        self.button_delete_uploading.setSizePolicy(sizePolicy)
        self.button_delete_uploading.setMinimumSize(QtCore.QSize(130, 30))
        self.button_delete_uploading.setMaximumSize(QtCore.QSize(16777215, 85))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(10)
        self.button_delete_uploading.setFont(font)
        self.button_delete_uploading.setStyleSheet("QPushButton {\n"
"    border: 2px solid rgb(52, 59, 72);\n"
"    border-radius: 5px;    \n"
"    background-color: rgb(52, 59, 72);\n"
"    color: white;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(57, 65, 80);\n"
"    border: 2px solid rgb(61, 70, 86);\n"
"}\n"
"QPushButton:pressed {    \n"
"    background-color: rgb(55, 0, 0);\n"
"    border: 2px solid rgb(77, 0, 0);\n"
"}")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/Icons/Resources/Icons/remove-circle-outline.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.button_delete_uploading.setIcon(icon5)
        self.button_delete_uploading.setIconSize(QtCore.QSize(22, 22))
        self.button_delete_uploading.setObjectName("button_delete_uploading")
        self.horizontalLayout_9.addWidget(self.button_delete_uploading)
        self.horizontalLayout_6.addWidget(self.frame_button_delete_uploading)
        self.frame_button_clear_uploading = QtWidgets.QFrame(self.frame_buttons_uploading_materials)
        self.frame_button_clear_uploading.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_button_clear_uploading.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_button_clear_uploading.setObjectName("frame_button_clear_uploading")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.frame_button_clear_uploading)
        self.horizontalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_10.setSpacing(0)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.button_clear_uploading = QtWidgets.QPushButton(self.frame_button_clear_uploading)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_clear_uploading.sizePolicy().hasHeightForWidth())
        self.button_clear_uploading.setSizePolicy(sizePolicy)
        self.button_clear_uploading.setMinimumSize(QtCore.QSize(130, 30))
        self.button_clear_uploading.setMaximumSize(QtCore.QSize(16777215, 85))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(10)
        self.button_clear_uploading.setFont(font)
        self.button_clear_uploading.setStyleSheet("QPushButton {\n"
"    border: 2px solid rgb(52, 59, 72);\n"
"    border-radius: 5px;    \n"
"    background-color: rgb(52, 59, 72);\n"
"    color: white;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(57, 65, 80);\n"
"    border: 2px solid rgb(61, 70, 86);\n"
"}\n"
"QPushButton:pressed {    \n"
"    background-color: rgb(200, 0, 0);\n"
"    border: 2px solid rgb(77, 0, 0);\n"
"}")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/Icons/Resources/Icons/trash-outline.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.button_clear_uploading.setIcon(icon6)
        self.button_clear_uploading.setIconSize(QtCore.QSize(22, 22))
        self.button_clear_uploading.setObjectName("button_clear_uploading")
        self.horizontalLayout_10.addWidget(self.button_clear_uploading)
        self.horizontalLayout_6.addWidget(self.frame_button_clear_uploading)
        self.verticalLayout_4.addWidget(self.frame_buttons_uploading_materials)
        self.verticalLayout.addWidget(self.frame_working_with_uploading_materials)
        self.frame_start_processing_button = QtWidgets.QFrame(self.left_frame)
        self.frame_start_processing_button.setMaximumSize(QtCore.QSize(16777215, 80))
        self.frame_start_processing_button.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_start_processing_button.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_start_processing_button.setObjectName("frame_start_processing_button")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.frame_start_processing_button)
        self.horizontalLayout_5.setContentsMargins(100, -1, 100, -1)
        self.horizontalLayout_5.setSpacing(0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.button_start_processing = QtWidgets.QPushButton(self.frame_start_processing_button)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_start_processing.sizePolicy().hasHeightForWidth())
        self.button_start_processing.setSizePolicy(sizePolicy)
        self.button_start_processing.setMinimumSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(16)
        self.button_start_processing.setFont(font)
        self.button_start_processing.setStyleSheet("QPushButton {\n"
"    border: 2px solid rgb(52, 59, 72);\n"
"    border-radius: 10px;    \n"
"    background-color: rgb(52, 59, 72);\n"
"    color: white;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(57, 65, 80);\n"
"    border: 2px solid rgb(61, 70, 86);\n"
"}\n"
"QPushButton:pressed {    \n"
"    background-color: rgb(35, 40, 49);\n"
"    border: 2px solid rgb(43, 50, 61);\n"
"}")
        self.button_start_processing.setObjectName("button_start_processing")
        self.horizontalLayout_5.addWidget(self.button_start_processing)
        self.verticalLayout.addWidget(self.frame_start_processing_button)
        self.frame_working_with_processed_materials = QtWidgets.QFrame(self.left_frame)
        self.frame_working_with_processed_materials.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_working_with_processed_materials.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_working_with_processed_materials.setObjectName("frame_working_with_processed_materials")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frame_working_with_processed_materials)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setSpacing(5)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.frame_list_processed_materials = QtWidgets.QFrame(self.frame_working_with_processed_materials)
        self.frame_list_processed_materials.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_list_processed_materials.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_list_processed_materials.setObjectName("frame_list_processed_materials")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.frame_list_processed_materials)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.frame_label_processed_materials = QtWidgets.QFrame(self.frame_list_processed_materials)
        self.frame_label_processed_materials.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_label_processed_materials.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_label_processed_materials.setObjectName("frame_label_processed_materials")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout(self.frame_label_processed_materials)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.label_processed_materials_list = QtWidgets.QLabel(self.frame_label_processed_materials)
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(12)
        self.label_processed_materials_list.setFont(font)
        self.label_processed_materials_list.setStyleSheet("color: rgb(230, 230, 230);")
        self.label_processed_materials_list.setObjectName("label_processed_materials_list")
        self.horizontalLayout_14.addWidget(self.label_processed_materials_list)
        self.verticalLayout_6.addWidget(self.frame_label_processed_materials)
        self.list_processed_materials = QtWidgets.QListWidget(self.frame_list_processed_materials)
        self.list_processed_materials.setMinimumSize(QtCore.QSize(0, 115))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(12)
        self.list_processed_materials.setFont(font)
        self.list_processed_materials.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.list_processed_materials.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.list_processed_materials.setObjectName("list_processed_materials")
        item = QtWidgets.QListWidgetItem()
        self.list_processed_materials.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.list_processed_materials.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.list_processed_materials.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.list_processed_materials.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.list_processed_materials.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.list_processed_materials.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.list_processed_materials.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.list_processed_materials.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.list_processed_materials.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.list_processed_materials.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.list_processed_materials.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.list_processed_materials.addItem(item)
        self.verticalLayout_6.addWidget(self.list_processed_materials)
        self.verticalLayout_5.addWidget(self.frame_list_processed_materials)
        self.frame_buttons_processed_materials = QtWidgets.QFrame(self.frame_working_with_processed_materials)
        self.frame_buttons_processed_materials.setMaximumSize(QtCore.QSize(16777215, 40))
        self.frame_buttons_processed_materials.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_buttons_processed_materials.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_buttons_processed_materials.setObjectName("frame_buttons_processed_materials")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.frame_buttons_processed_materials)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setSpacing(3)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.frame_button_open_folder = QtWidgets.QFrame(self.frame_buttons_processed_materials)
        self.frame_button_open_folder.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_button_open_folder.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_button_open_folder.setObjectName("frame_button_open_folder")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.frame_button_open_folder)
        self.horizontalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_11.setSpacing(0)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.button_open_folder_process = QtWidgets.QPushButton(self.frame_button_open_folder)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_open_folder_process.sizePolicy().hasHeightForWidth())
        self.button_open_folder_process.setSizePolicy(sizePolicy)
        self.button_open_folder_process.setMinimumSize(QtCore.QSize(130, 30))
        self.button_open_folder_process.setMaximumSize(QtCore.QSize(16777215, 85))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(10)
        self.button_open_folder_process.setFont(font)
        self.button_open_folder_process.setStyleSheet("QPushButton {\n"
"    border: 2px solid rgb(52, 59, 72);\n"
"    border-radius: 5px;    \n"
"    background-color: rgb(52, 59, 72);\n"
"    color: white;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(57, 65, 80);\n"
"    border: 2px solid rgb(61, 70, 86);\n"
"}\n"
"QPushButton:pressed {    \n"
"    background-color: rgb(35, 40, 49);\n"
"    border: 2px solid rgb(43, 50, 61);\n"
"}")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/Icons/Resources/Icons/folder.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.button_open_folder_process.setIcon(icon7)
        self.button_open_folder_process.setIconSize(QtCore.QSize(22, 22))
        self.button_open_folder_process.setObjectName("button_open_folder_process")
        self.horizontalLayout_11.addWidget(self.button_open_folder_process)
        self.horizontalLayout_7.addWidget(self.frame_button_open_folder)
        self.frame_spacer_processed = QtWidgets.QFrame(self.frame_buttons_processed_materials)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_spacer_processed.sizePolicy().hasHeightForWidth())
        self.frame_spacer_processed.setSizePolicy(sizePolicy)
        self.frame_spacer_processed.setMinimumSize(QtCore.QSize(0, 0))
        self.frame_spacer_processed.setSizeIncrement(QtCore.QSize(10, 0))
        self.frame_spacer_processed.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_spacer_processed.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_spacer_processed.setObjectName("frame_spacer_processed")
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout(self.frame_spacer_processed)
        self.horizontalLayout_16.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_16.setSpacing(0)
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.horizontalLayout_7.addWidget(self.frame_spacer_processed)
        self.frame_button_delete_processed = QtWidgets.QFrame(self.frame_buttons_processed_materials)
        self.frame_button_delete_processed.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_button_delete_processed.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_button_delete_processed.setObjectName("frame_button_delete_processed")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.frame_button_delete_processed)
        self.horizontalLayout_12.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_12.setSpacing(0)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.button_delete_processed = QtWidgets.QPushButton(self.frame_button_delete_processed)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_delete_processed.sizePolicy().hasHeightForWidth())
        self.button_delete_processed.setSizePolicy(sizePolicy)
        self.button_delete_processed.setMinimumSize(QtCore.QSize(130, 30))
        self.button_delete_processed.setMaximumSize(QtCore.QSize(16777215, 85))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(10)
        self.button_delete_processed.setFont(font)
        self.button_delete_processed.setStyleSheet("QPushButton {\n"
"    border: 2px solid rgb(52, 59, 72);\n"
"    border-radius: 5px;    \n"
"    background-color: rgb(52, 59, 72);\n"
"    color: white;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(57, 65, 80);\n"
"    border: 2px solid rgb(61, 70, 86);\n"
"}\n"
"QPushButton:pressed {    \n"
"    background-color: rgb(55, 0, 0);\n"
"    border: 2px solid rgb(77, 0, 0);\n"
"}")
        self.button_delete_processed.setIcon(icon5)
        self.button_delete_processed.setIconSize(QtCore.QSize(22, 22))
        self.button_delete_processed.setObjectName("button_delete_processed")
        self.horizontalLayout_12.addWidget(self.button_delete_processed)
        self.horizontalLayout_7.addWidget(self.frame_button_delete_processed)
        self.frame_button_clear_processed = QtWidgets.QFrame(self.frame_buttons_processed_materials)
        self.frame_button_clear_processed.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_button_clear_processed.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_button_clear_processed.setObjectName("frame_button_clear_processed")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout(self.frame_button_clear_processed)
        self.horizontalLayout_13.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_13.setSpacing(0)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.button_clear_processed = QtWidgets.QPushButton(self.frame_button_clear_processed)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_clear_processed.sizePolicy().hasHeightForWidth())
        self.button_clear_processed.setSizePolicy(sizePolicy)
        self.button_clear_processed.setMinimumSize(QtCore.QSize(130, 30))
        self.button_clear_processed.setMaximumSize(QtCore.QSize(16777215, 85))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(10)
        self.button_clear_processed.setFont(font)
        self.button_clear_processed.setStyleSheet("QPushButton {\n"
"    border: 2px solid rgb(52, 59, 72);\n"
"    border-radius: 5px;    \n"
"    background-color: rgb(52, 59, 72);\n"
"    color: white;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(57, 65, 80);\n"
"    border: 2px solid rgb(61, 70, 86);\n"
"}\n"
"QPushButton:pressed {    \n"
"    background-color: rgb(200, 0, 0);\n"
"    border: 2px solid rgb(77, 0, 0);\n"
"}\n"
"")
        self.button_clear_processed.setIcon(icon6)
        self.button_clear_processed.setIconSize(QtCore.QSize(22, 22))
        self.button_clear_processed.setObjectName("button_clear_processed")
        self.horizontalLayout_13.addWidget(self.button_clear_processed)
        self.horizontalLayout_7.addWidget(self.frame_button_clear_processed)
        self.verticalLayout_5.addWidget(self.frame_buttons_processed_materials)
        self.verticalLayout.addWidget(self.frame_working_with_processed_materials)
        self.horizontalLayout_17.addWidget(self.left_frame)
        self.right_frame = QtWidgets.QFrame(self.frame_main_functional)
        self.right_frame.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.right_frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.right_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.right_frame.setObjectName("right_frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.right_frame)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(10)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame_preview = QtWidgets.QFrame(self.right_frame)
        self.frame_preview.setStyleSheet("")
        self.frame_preview.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_preview.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_preview.setObjectName("frame_preview")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_preview)
        self.verticalLayout_3.setContentsMargins(10, 0, 10, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.frame_preview_text_label = QtWidgets.QFrame(self.frame_preview)
        self.frame_preview_text_label.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_preview_text_label.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_preview_text_label.setObjectName("frame_preview_text_label")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout(self.frame_preview_text_label)
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.label_image_status = QtWidgets.QLabel(self.frame_preview_text_label)
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(12)
        self.label_image_status.setFont(font)
        self.label_image_status.setStyleSheet("color: rgb(230, 230, 230);")
        self.label_image_status.setObjectName("label_image_status")
        self.horizontalLayout_15.addWidget(self.label_image_status)
        self.verticalLayout_3.addWidget(self.frame_preview_text_label)
        self.label_photo_preview = QtWidgets.QLabel(self.frame_preview)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_photo_preview.sizePolicy().hasHeightForWidth())
        self.label_photo_preview.setSizePolicy(sizePolicy)
        self.label_photo_preview.setMinimumSize(QtCore.QSize(0, 0))
        self.label_photo_preview.setStyleSheet("background-color: rgb(20, 20, 20);\n"
"border-radius: 3px;\n"
"border: 2px solid rgb(64, 71, 88);")
        self.label_photo_preview.setText("")
        self.label_photo_preview.setTextFormat(QtCore.Qt.AutoText)
        self.label_photo_preview.setScaledContents(True)
        self.label_photo_preview.setAlignment(QtCore.Qt.AlignCenter)
        self.label_photo_preview.setWordWrap(True)
        self.label_photo_preview.setOpenExternalLinks(False)
        self.label_photo_preview.setObjectName("label_photo_preview")
        self.verticalLayout_3.addWidget(self.label_photo_preview)
        self.verticalLayout_2.addWidget(self.frame_preview)
        self.frame_answer_string = QtWidgets.QFrame(self.right_frame)
        self.frame_answer_string.setMinimumSize(QtCore.QSize(0, 0))
        self.frame_answer_string.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.frame_answer_string.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_answer_string.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_answer_string.setObjectName("frame_answer_string")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.frame_answer_string)
        self.verticalLayout_9.setContentsMargins(10, 0, 10, 0)
        self.verticalLayout_9.setSpacing(0)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.frame_answer_from_csv = QtWidgets.QFrame(self.frame_answer_string)
        self.frame_answer_from_csv.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_answer_from_csv.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_answer_from_csv.setObjectName("frame_answer_from_csv")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.frame_answer_from_csv)
        self.verticalLayout_10.setContentsMargins(0, 0, 0, 10)
        self.verticalLayout_10.setSpacing(0)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.frame_answer_text = QtWidgets.QFrame(self.frame_answer_from_csv)
        self.frame_answer_text.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_answer_text.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_answer_text.setObjectName("frame_answer_text")
        self.horizontalLayout_23 = QtWidgets.QHBoxLayout(self.frame_answer_text)
        self.horizontalLayout_23.setObjectName("horizontalLayout_23")
        self.label_image_status_2 = QtWidgets.QLabel(self.frame_answer_text)
        self.label_image_status_2.setMinimumSize(QtCore.QSize(0, 25))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(12)
        self.label_image_status_2.setFont(font)
        self.label_image_status_2.setStyleSheet("color: rgb(230, 230, 230);")
        self.label_image_status_2.setObjectName("label_image_status_2")
        self.horizontalLayout_23.addWidget(self.label_image_status_2)
        self.verticalLayout_10.addWidget(self.frame_answer_text)
        self.lineEdit_answer = QtWidgets.QLineEdit(self.frame_answer_from_csv)
        self.lineEdit_answer.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(12)
        self.lineEdit_answer.setFont(font)
        self.lineEdit_answer.setStyleSheet("color: white;")
        self.lineEdit_answer.setText("")
        self.lineEdit_answer.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.lineEdit_answer.setReadOnly(True)
        self.lineEdit_answer.setClearButtonEnabled(False)
        self.lineEdit_answer.setObjectName("lineEdit_answer")
        self.verticalLayout_10.addWidget(self.lineEdit_answer)
        self.verticalLayout_9.addWidget(self.frame_answer_from_csv)
        self.verticalLayout_2.addWidget(self.frame_answer_string)
        self.frame_preview_buttons = QtWidgets.QFrame(self.right_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_preview_buttons.sizePolicy().hasHeightForWidth())
        self.frame_preview_buttons.setSizePolicy(sizePolicy)
        self.frame_preview_buttons.setMinimumSize(QtCore.QSize(0, 100))
        self.frame_preview_buttons.setMaximumSize(QtCore.QSize(16777215, 100))
        self.frame_preview_buttons.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_preview_buttons.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_preview_buttons.setObjectName("frame_preview_buttons")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_preview_buttons)
        self.horizontalLayout_3.setContentsMargins(40, 0, 40, 0)
        self.horizontalLayout_3.setSpacing(60)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.button_previous_image = QtWidgets.QPushButton(self.frame_preview_buttons)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_previous_image.sizePolicy().hasHeightForWidth())
        self.button_previous_image.setSizePolicy(sizePolicy)
        self.button_previous_image.setMinimumSize(QtCore.QSize(100, 40))
        self.button_previous_image.setMaximumSize(QtCore.QSize(100, 100))
        self.button_previous_image.setStyleSheet("QPushButton { \n"
"    background-color: rgb(52, 59, 72);\n"
"    color: white;\n"
"    border-radius: 50px;\n"
"    border: 5px solid rgb(82, 89, 102);\n"
"    background-position: center;\n"
"    background-repeat: no-repeat;\n"
"}\n"
"\n"
"QPushButton::hover {\n"
"    background-color: rgb(57, 65, 80);\n"
"}\n"
"\n"
"QPushButton::pressed {\n"
"    background-color: rgb(35, 40, 49);\n"
"}")
        self.button_previous_image.setText("")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/Icons/Resources/Icons/arrow-back-outline.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.button_previous_image.setIcon(icon8)
        self.button_previous_image.setIconSize(QtCore.QSize(48, 48))
        self.button_previous_image.setObjectName("button_previous_image")
        self.horizontalLayout_3.addWidget(self.button_previous_image)
        self.button_next_image = QtWidgets.QPushButton(self.frame_preview_buttons)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_next_image.sizePolicy().hasHeightForWidth())
        self.button_next_image.setSizePolicy(sizePolicy)
        self.button_next_image.setMinimumSize(QtCore.QSize(100, 40))
        self.button_next_image.setMaximumSize(QtCore.QSize(100, 100))
        self.button_next_image.setStyleSheet("QPushButton { \n"
"    background-color: rgb(52, 59, 72);\n"
"    color: white;\n"
"    border-radius: 50px;\n"
"    border: 5px solid rgb(82, 89, 102);\n"
"    background-position: center;\n"
"    background-repeat: no-repeat;\n"
"}\n"
"\n"
"QPushButton::hover {\n"
"    background-color: rgb(57, 65, 80);\n"
"}\n"
"\n"
"QPushButton::pressed {\n"
"    background-color: rgb(35, 40, 49);\n"
"}")
        self.button_next_image.setText("")
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/Icons/Resources/Icons/arrow-forward-outline.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.button_next_image.setIcon(icon9)
        self.button_next_image.setIconSize(QtCore.QSize(48, 48))
        self.button_next_image.setObjectName("button_next_image")
        self.horizontalLayout_3.addWidget(self.button_next_image)
        self.verticalLayout_2.addWidget(self.frame_preview_buttons, 0, QtCore.Qt.AlignHCenter)
        self.horizontalLayout_17.addWidget(self.right_frame)
        self.verticalLayout_8.addWidget(self.frame_main_functional)
        self.horizontalLayout.addWidget(self.main_frame)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Определение Гренландского Кита"))
        self.label_title.setText(_translate("MainWindow", "Определение особи гренландского кита"))
        self.button_hide.setToolTip(_translate("MainWindow", "<html><head/><body><p>Скрыть окно</p></body></html>"))
        self.button_minimize.setToolTip(_translate("MainWindow", "<html><head/><body><p>Изменить размер окна</p></body></html>"))
        self.button_close.setToolTip(_translate("MainWindow", "<html><head/><body><p>Закрыть приложение</p></body></html>"))
        self.label_uploading_materials_list.setText(_translate("MainWindow", "Загруженные изображения"))
        self.list_uploading_materials.setToolTip(_translate("MainWindow", "<html><head/><body><p>Список с изображениями, которые предстоит обработать. </p><p>Поддерживаемые форматы изображений: \'.jpg\', \'.jpeg\', \'.png\'.</p></body></html>"))
        __sortingEnabled = self.list_uploading_materials.isSortingEnabled()
        self.list_uploading_materials.setSortingEnabled(False)
        item = self.list_uploading_materials.item(0)
        item.setText(_translate("MainWindow", "1.jped"))
        item = self.list_uploading_materials.item(1)
        item.setText(_translate("MainWindow", "95872395239562389562395252359326509230535723089523095230895230523523509325023560325239052309573209583250263503250923560235023652035623908588235.jpeg"))
        item = self.list_uploading_materials.item(2)
        item.setText(_translate("MainWindow", "2.jped"))
        item = self.list_uploading_materials.item(3)
        item.setText(_translate("MainWindow", "3.jpeg"))
        item = self.list_uploading_materials.item(4)
        item.setText(_translate("MainWindow", "4.jpeg"))
        item = self.list_uploading_materials.item(5)
        item.setText(_translate("MainWindow", "5.png"))
        item = self.list_uploading_materials.item(6)
        item.setText(_translate("MainWindow", "6.jpeg"))
        item = self.list_uploading_materials.item(7)
        item.setText(_translate("MainWindow", "7.jpeg"))
        item = self.list_uploading_materials.item(8)
        item.setText(_translate("MainWindow", "8.jpeg"))
        item = self.list_uploading_materials.item(9)
        item.setText(_translate("MainWindow", "9.jpeg"))
        item = self.list_uploading_materials.item(10)
        item.setText(_translate("MainWindow", "10.jpeg"))
        item = self.list_uploading_materials.item(11)
        item.setText(_translate("MainWindow", "11.jpeg"))
        item = self.list_uploading_materials.item(12)
        item.setText(_translate("MainWindow", "12.png"))
        self.list_uploading_materials.setSortingEnabled(__sortingEnabled)
        self.button_add_uploading.setToolTip(_translate("MainWindow", "<html><head/><body><p>Указать папку с изображениями для начала работы</p></body></html>"))
        self.button_add_uploading.setText(_translate("MainWindow", "Добавить элемент"))
        self.button_delete_uploading.setToolTip(_translate("MainWindow", "<html><head/><body><p>Удалить выбранный элемент из списка</p></body></html>"))
        self.button_delete_uploading.setText(_translate("MainWindow", "Удалить элемент"))
        self.button_clear_uploading.setToolTip(_translate("MainWindow", "<html><head/><body><p>Удалить все элементы из списка</p></body></html>"))
        self.button_clear_uploading.setText(_translate("MainWindow", "Очистить список"))
        self.button_start_processing.setToolTip(_translate("MainWindow", "<html><head/><body><p>Запустить процесс обработки</p></body></html>"))
        self.button_start_processing.setText(_translate("MainWindow", "Обработать"))
        self.label_processed_materials_list.setText(_translate("MainWindow", "Обработанные изображения"))
        self.list_processed_materials.setToolTip(_translate("MainWindow", "<html><head/><body><p>Список с уже обработанными изображениями.</p><p>Поддерживаемые форматы изображений: \'.jpg\', \'.jpeg\', \'.png\'.</p></body></html>"))
        __sortingEnabled = self.list_processed_materials.isSortingEnabled()
        self.list_processed_materials.setSortingEnabled(False)
        item = self.list_processed_materials.item(0)
        item.setText(_translate("MainWindow", "1_processed.jpeg"))
        item = self.list_processed_materials.item(1)
        item.setText(_translate("MainWindow", "2_processed.jpeg"))
        item = self.list_processed_materials.item(2)
        item.setText(_translate("MainWindow", "3_processed.jpeg"))
        item = self.list_processed_materials.item(3)
        item.setText(_translate("MainWindow", "532345235235"))
        item = self.list_processed_materials.item(4)
        item.setText(_translate("MainWindow", "32452345"))
        item = self.list_processed_materials.item(5)
        item.setText(_translate("MainWindow", "32"))
        item = self.list_processed_materials.item(6)
        item.setText(_translate("MainWindow", "5235"))
        item = self.list_processed_materials.item(7)
        item.setText(_translate("MainWindow", "325"))
        item = self.list_processed_materials.item(8)
        item.setText(_translate("MainWindow", "235"))
        item = self.list_processed_materials.item(9)
        item.setText(_translate("MainWindow", "32"))
        item = self.list_processed_materials.item(10)
        item.setText(_translate("MainWindow", "523"))
        item = self.list_processed_materials.item(11)
        item.setText(_translate("MainWindow", "52345234532"))
        self.list_processed_materials.setSortingEnabled(__sortingEnabled)
        self.button_open_folder_process.setToolTip(_translate("MainWindow", "<html><head/><body><p>Открыть папку с обработанными изображениями</p></body></html>"))
        self.button_open_folder_process.setText(_translate("MainWindow", "Открыть папку"))
        self.button_delete_processed.setToolTip(_translate("MainWindow", "<html><head/><body><p>Удалить выбранный элемент из списка</p></body></html>"))
        self.button_delete_processed.setText(_translate("MainWindow", "Удалить элемент"))
        self.button_clear_processed.setToolTip(_translate("MainWindow", "<html><head/><body><p>Удалить все элементы из списка</p></body></html>"))
        self.button_clear_processed.setText(_translate("MainWindow", "Очистить список"))
        self.label_image_status.setText(_translate("MainWindow", "Предпросмотр"))
        self.label_photo_preview.setToolTip(_translate("MainWindow", "<html><head/><body><p>Предпросмотр изображения</p></body></html>"))
        self.label_image_status_2.setText(_translate("MainWindow", "Результат"))
        self.lineEdit_answer.setToolTip(_translate("MainWindow", "<html><head/><body><p>Результат обработки в одну строку</p></body></html>"))
        self.lineEdit_answer.setPlaceholderText(_translate("MainWindow", "Здесь будет ваш результат..."))
        self.button_previous_image.setToolTip(_translate("MainWindow", "<html><head/><body><p>Открыть предыдущее изображение</p></body></html>"))
        self.button_next_image.setToolTip(_translate("MainWindow", "<html><head/><body><p>Открыть следующее изображение</p></body></html>"))
import Resources_rc
